version: "3.6"
services:
  postgres:
    image: postgres
  traefik:
    image: traefik
  redis:
    image: redis:4
    healthcheck:
      test: redis-cli ping
      interval: 5s
      timeout: 10s
      retries: 5
  rabbitmq:
    image: rabbitmq
    healthcheck:
      test: rabbitmqctl status
      interval: 5s
      timeout: 10s
      retries: 5
