project_name: rae

builds:
- env:
  - CGO_ENABLED=0
  binary: rae
  ldflags:
   - -X github.com/LGUG2Z/rae/cli.Version={{ .Version }} -X github.com/LGUG2Z/rae/cli.Commit={{ .Commit }}
  goarch:
    - amd64

archive:
  files:
    - bash_autocomplete
    - zsh_autocomplete

brew:
  name: rae
  github:
    owner: LGUG2Z
    name: homebrew-tap
  folder: Formula
  homepage: "https://github.com/LGUG2Z/rae"
  description: "A docker-compose development environment orchestrator"
  dependencies:
  - docker
  test: |
    system "#{bin}/rae --version"
  install: |
    bin.install "rae"
    bash_completion.install "bash_autocomplete"
    zsh_completion.install "zsh_autocomplete"

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-snapshot"

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
